ENVIROMENT_NUM_NODES=10
ENIROMENT_DENSITY=50
SIMULATION_STEPS=50
SIMULATION_OUT_DIR="Test_Training"
AGENT_MAX_EDGES=5
LN_DEFAULT_CHANNEL_COST=0
AGENT_NAME="Naive"

# TODO: Find the default values
LND_DEFAULT_POLICY = {"time_lock_delta": 144, "fee_base_msat": 1000, "fee_rate_milli_msat": 0.001}